name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.14
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  layout: ^1.0.5
  type_text: ^1.0.5
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/personal/
    - assets/images/van_gogh/
    - assets/images/projects/
    - assets/images/tools/
    # Documents
    - assets/documents/certificates/
